version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: itau-bff
    env_file:
      - .env
    ports:
      - ${PORT:-3001}:${PORT:-3001}
    volumes:
      - .:/usr/api
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysqldb:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASSWORD}
    volumes:
      - ./.docker/db/bddata:/var/lib/mysql
      - ./.docker/db/bdimport:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
